import comp from "C:/Users/Lenovo/stormbpmn-documentation/src/.vuepress/.temp/pages/bpmn/8_lesson.html.vue"
const data = JSON.parse("{\"path\":\"/bpmn/8_lesson.html\",\"title\":\"8 урок: Хороший стиль BPMN\",\"lang\":\"ru-RU\",\"frontmatter\":{\"index\":true},\"headers\":[{\"level\":2,\"title\":\"Видеоверсия\",\"slug\":\"видеоверсия\",\"link\":\"#видеоверсия\",\"children\":[]},{\"level\":2,\"title\":\"Зачем нужен хороший стиль\",\"slug\":\"зачем-нужен-хорошии-стиль\",\"link\":\"#зачем-нужен-хорошии-стиль\",\"children\":[]},{\"level\":2,\"title\":\"Элементы хорошего стиля\",\"slug\":\"элементы-хорошего-стиля\",\"link\":\"#элементы-хорошего-стиля\",\"children\":[{\"level\":3,\"title\":\"Happy path\",\"slug\":\"happy-path\",\"link\":\"#happy-path\",\"children\":[]},{\"level\":3,\"title\":\"Наименование задачи “Глагол” + “Существительное”\",\"slug\":\"наименование-задачи-глагол-существительное\",\"link\":\"#наименование-задачи-глагол-существительное\",\"children\":[]},{\"level\":3,\"title\":\"Процесс без дорожек\",\"slug\":\"процесс-без-дорожек\",\"link\":\"#процесс-без-дорожек\",\"children\":[]},{\"level\":3,\"title\":\"Много заверающих событий\",\"slug\":\"много-заверающих-событии\",\"link\":\"#много-заверающих-событии\",\"children\":[]},{\"level\":3,\"title\":\"Нумерация шлюзов\",\"slug\":\"нумерация-шлюзов\",\"link\":\"#нумерация-шлюзов\",\"children\":[]},{\"level\":3,\"title\":\"Путь по-умолчанию\",\"slug\":\"путь-по-умолчанию\",\"link\":\"#путь-по-умолчанию\",\"children\":[]},{\"level\":3,\"title\":\"Один вход, один выход в задаче\",\"slug\":\"один-вход-один-выход-в-задаче\",\"link\":\"#один-вход-один-выход-в-задаче\",\"children\":[]},{\"level\":3,\"title\":\"Не используйте условный переход\",\"slug\":\"не-используите-условныи-переход\",\"link\":\"#не-используите-условныи-переход\",\"children\":[]}]},{\"level\":2,\"title\":\"Факультатив\",\"slug\":\"факультатив\",\"link\":\"#факультатив\",\"children\":[]}],\"git\":{\"createdTime\":1715029278000,\"updatedTime\":1740668561000,\"contributors\":[{\"name\":\"Denis Kotov\",\"email\":\"31292696+KotskinKotskin@users.noreply.github.com\",\"commits\":4}]},\"readingTime\":{\"minutes\":1.62,\"words\":486},\"filePathRelative\":\"bpmn/8_lesson.md\",\"localizedDate\":\"7 мая 2024 г.\",\"excerpt\":\"\\n<p>Вы уже умеете использовать BPMN и знаете, как проверять корректность схем. Этого ещё недостаточно, чтобы делать адекватные и читаемые диаграммы. Сегодня поговорим про “хороший стиль” моделирования и о том, что нужно обязательно учитывать, когда делаете схемы.</p>\\n<h2>Видеоверсия</h2>\\n<iframe width=\\\"560\\\" height=\\\"315\\\" src=\\\"https://www.youtube.com/embed/KmwUmINlzGo?si=F9C03KODLxb-FJcz\\\" title=\\\"YouTube video player\\\" frameborder=\\\"0\\\" allow=\\\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\\\" referrerpolicy=\\\"strict-origin-when-cross-origin\\\" allowfullscreen=\\\"\\\"></iframe>\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
