import comp from "D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/Установка/FULL_INSTALL.html.vue"
const data = JSON.parse("{\"path\":\"/enterprise/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0/FULL_INSTALL.html\",\"title\":\"Production-ready установка\",\"lang\":\"ru-RU\",\"frontmatter\":{\"order\":-1,\"dir\":{\"link\":true},\"index\":true,\"icon\":\"\"},\"headers\":[{\"level\":2,\"title\":\"Балансер\",\"slug\":\"балансер\",\"link\":\"#балансер\",\"children\":[]},{\"level\":2,\"title\":\"S3-хранилище\",\"slug\":\"s3-хранилище\",\"link\":\"#s3-хранилище\",\"children\":[]},{\"level\":2,\"title\":\"Plantuml-сервер\",\"slug\":\"plantuml-сервер\",\"link\":\"#plantuml-сервер\",\"children\":[]},{\"level\":2,\"title\":\"Сервис конвератации документов\",\"slug\":\"сервис-конвератации-документов\",\"link\":\"#сервис-конвератации-документов\",\"children\":[]},{\"level\":2,\"title\":\"Подключить STORM к системам мониторинга и обеспечить резервное копирование\",\"slug\":\"подключить-storm-к-системам-мониторинга-и-обеспечить-резервное-копирование\",\"link\":\"#подключить-storm-к-системам-мониторинга-и-обеспечить-резервное-копирование\",\"children\":[]},{\"level\":2,\"title\":\"Хардендинг и SIEM\",\"slug\":\"хардендинг-и-siem\",\"link\":\"#хардендинг-и-siem\",\"children\":[]},{\"level\":2,\"title\":\"Обеспечение высокой доступности\",\"slug\":\"обеспечение-высокои-доступности\",\"link\":\"#обеспечение-высокои-доступности\",\"children\":[]},{\"level\":2,\"title\":\"Выбрать провайдер почты\",\"slug\":\"выбрать-проваидер-почты\",\"link\":\"#выбрать-проваидер-почты\",\"children\":[{\"level\":3,\"title\":\"Нужны красивые письма\",\"slug\":\"нужны-красивые-письма\",\"link\":\"#нужны-красивые-письма\",\"children\":[]},{\"level\":3,\"title\":\"Не нужны красивые письма\",\"slug\":\"не-нужны-красивые-письма\",\"link\":\"#не-нужны-красивые-письма\",\"children\":[]}]},{\"level\":2,\"title\":\"Настройка бизнес-параметров\",\"slug\":\"настроика-бизнес-параметров\",\"link\":\"#настроика-бизнес-параметров\",\"children\":[]}],\"git\":{\"createdTime\":1729001299000,\"updatedTime\":1750433983000,\"contributors\":[{\"name\":\"Denis Kotov\",\"email\":\"31292696+KotskinKotskin@users.noreply.github.com\",\"commits\":5}]},\"readingTime\":{\"minutes\":4.25,\"words\":1274},\"filePathRelative\":\"enterprise/Установка/FULL_INSTALL.md\",\"localizedDate\":\"15 октября 2024 г.\",\"excerpt\":\"\\n<p>Для полноценной работы необходимо:</p>\\n<ul>\\n<li>Поставить балансер и настроить SSL.</li>\\n<li>Развернуть S3-хранилище для хранения картинок и шаблонов документов.</li>\\n<li>Развернуть Plantuml-сервер.</li>\\n<li>Развернуть сервис конвертации файлов.</li>\\n<li>Подключить Storm к системам мониторинга и алертов.</li>\\n<li>Обеспечить резервное копирование.</li>\\n<li>\\\"Захардендить\\\" настройки безопасности.</li>\\n<li>Подключить SIEM-логирование.</li>\\n<li>Выбрать провайдер почты и настроить его.</li>\\n<li>Настроить бизнес-параметры в административном интерфейсе</li>\\n</ul>\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
