export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/get-started.html", { loader: () => import(/* webpackChunkName: "get-started.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/get-started.html.js"), meta: {"t":"С чего начать","i":"play","O":1} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/index.html.js"), meta: {"t":"Главная страница","O":0} }],
  ["/bpmn/1_lesson.html", { loader: () => import(/* webpackChunkName: "1_lesson.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/bpmn/1_lesson.html.js"), meta: {"t":"1 урок: BPM, BPMN, BPMS"} }],
  ["/bpmn/2_lesson.html", { loader: () => import(/* webpackChunkName: "2_lesson.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/bpmn/2_lesson.html.js"), meta: {"t":"2 урок:  Понятие бизнес-процесса и экзепляра процесса"} }],
  ["/bpmn/3_lesson.html", { loader: () => import(/* webpackChunkName: "3_lesson.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/bpmn/3_lesson.html.js"), meta: {"t":"3 урок:  3 уровня моделирования BPMN-схем"} }],
  ["/bpmn/4_lesson.html", { loader: () => import(/* webpackChunkName: "4_lesson.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/bpmn/4_lesson.html.js"), meta: {"t":"4 урок: BPMN для \"чайников\". Базовые элементы. (1/3)"} }],
  ["/bpmn/5_lesson.html", { loader: () => import(/* webpackChunkName: "5_lesson.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/bpmn/5_lesson.html.js"), meta: {"t":"5 урок: BPMN для \"чайников\". Базовые элементы. (2/3)"} }],
  ["/bpmn/6_lesson.html", { loader: () => import(/* webpackChunkName: "6_lesson.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/bpmn/6_lesson.html.js"), meta: {"t":"6 урок: BPMN для \"чайников\". Пулы и дорожки. (3/3)"} }],
  ["/bpmn/7_lesson.html", { loader: () => import(/* webpackChunkName: "7_lesson.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/bpmn/7_lesson.html.js"), meta: {"t":"7 урок: Проверка BPMN-схем на корректность"} }],
  ["/bpmn/8_lesson.html", { loader: () => import(/* webpackChunkName: "8_lesson.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/bpmn/8_lesson.html.js"), meta: {"t":"8 урок: Хороший стиль BPMN"} }],
  ["/bpmn/9_lesson.html", { loader: () => import(/* webpackChunkName: "9_lesson.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/bpmn/9_lesson.html.js"), meta: {"t":"9 урок: Разбираем и улучшаем схему BPMN"} }],
  ["/bpmn/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/bpmn/index.html.js"), meta: {"t":"Что такое BPMN","i":"circle-nodes","O":-1} }],
  ["/enterprise/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/index.html.js"), meta: {"t":"Enterprise-версия","i":"file","O":-3} }],
  ["/features_new_storm/0_home-page.html", { loader: () => import(/* webpackChunkName: "0_home-page.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/0_home-page.html.js"), meta: {"t":"Главная страница","i":null,"O":1} }],
  ["/features_new_storm/10_plant_uml.html", { loader: () => import(/* webpackChunkName: "10_plant_uml.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/10_plant_uml.html.js"), meta: {"t":"New Шторм. Редактор UML","O":10} }],
  ["/features_new_storm/20_FAQ.html", { loader: () => import(/* webpackChunkName: "20_FAQ.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/20_FAQ.html.js"), meta: {"t":"New Шторм. FAQ - ответы на часто задаваемые вопросы","O":20} }],
  ["/features_new_storm/2_group-editor.html", { loader: () => import(/* webpackChunkName: "2_group-editor.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/2_group-editor.html.js"), meta: {"t":"New Шторм. Редактор групп процессов","O":2} }],
  ["/features_new_storm/3_org-chart-editor.html", { loader: () => import(/* webpackChunkName: "3_org-chart-editor.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/3_org-chart-editor.html.js"), meta: {"t":"New Шторм. Редактор оргструктуры","O":3} }],
  ["/features_new_storm/4_assignees.html", { loader: () => import(/* webpackChunkName: "4_assignees.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/4_assignees.html.js"), meta: {"t":"New Шторм. Роли","O":4} }],
  ["/features_new_storm/6_reglaments.html", { loader: () => import(/* webpackChunkName: "6_reglaments.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/6_reglaments.html.js"), meta: {"t":"New Шторм. Регламенты","O":6} }],
  ["/features_new_storm/7_folders.html", { loader: () => import(/* webpackChunkName: "7_folders.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/7_folders.html.js"), meta: {"t":"New Шторм. Папки и теги","O":7} }],
  ["/features_new_storm/8_comments.html", { loader: () => import(/* webpackChunkName: "8_comments.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/8_comments.html.js"), meta: {"t":"New Шторм. Комментарии","O":8} }],
  ["/features_new_storm/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/index.html.js"), meta: {"t":"Функции системы","i":"star","O":-10} }],
  ["/features/0_home-page.html", { loader: () => import(/* webpackChunkName: "0_home-page.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/0_home-page.html.js"), meta: {"t":"Главная страница","i":null,"O":1} }],
  ["/features/10_Diagram_scoring.html", { loader: () => import(/* webpackChunkName: "10_Diagram_scoring.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/10_Diagram_scoring.html.js"), meta: {"t":"Оценка качества диаграмм","O":10} }],
  ["/features/1_bpmn-editor.html", { loader: () => import(/* webpackChunkName: "1_bpmn-editor.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/1_bpmn-editor.html.js"), meta: {"t":"Бизнес-процессы в BPMN","i":"heart","O":2} }],
  ["/features/2_group-editor.html", { loader: () => import(/* webpackChunkName: "2_group-editor.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/2_group-editor.html.js"), meta: {"t":"Редактор групп процессов","O":2} }],
  ["/features/3_org-chart-editor.html", { loader: () => import(/* webpackChunkName: "3_org-chart-editor.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/3_org-chart-editor.html.js"), meta: {"t":"Редактор оргструктуры","O":3} }],
  ["/features/4_assignees.html", { loader: () => import(/* webpackChunkName: "4_assignees.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/4_assignees.html.js"), meta: {"t":"Роли","O":4} }],
  ["/features/4_plant_uml.html", { loader: () => import(/* webpackChunkName: "4_plant_uml.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/4_plant_uml.html.js"), meta: {"t":"Редактор UML","O":4} }],
  ["/features/5_elements-architecture.html", { loader: () => import(/* webpackChunkName: "5_elements-architecture.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/5_elements-architecture.html.js"), meta: {"t":"Элементы архитектуры","O":5} }],
  ["/features/6_reglaments.html", { loader: () => import(/* webpackChunkName: "6_reglaments.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/6_reglaments.html.js"), meta: {"t":"Регламенты","O":6} }],
  ["/features/7_folders.html", { loader: () => import(/* webpackChunkName: "7_folders.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/7_folders.html.js"), meta: {"t":"Папки и теги","O":7} }],
  ["/features/8_comments.html", { loader: () => import(/* webpackChunkName: "8_comments.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/8_comments.html.js"), meta: {"t":"Комментарии","O":8} }],
  ["/features/9_FAQ.html", { loader: () => import(/* webpackChunkName: "9_FAQ.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/9_FAQ.html.js"), meta: {"t":"FAQ - ответы на часто задаваемые вопросы","O":9} }],
  ["/features/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features/index.html.js"), meta: {"t":"Функции системы","i":"star","O":3} }],
  ["/real-life-scenarios/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/real-life-scenarios/index.html.js"), meta: {"t":"В реальной жизни","i":"user","O":1} }],
  ["/support/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/support/index.html.js"), meta: {"t":"Тех.поддержка и администрирование","i":"handshake-angle","O":-1} }],
  ["/team-work/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/team-work/index.html.js"), meta: {"t":"Совместная работа","i":"user-group","O":-3} }],
  ["/enterprise/REST%20API/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/REST API/index.html.js"), meta: {"t":"Rest API","i":"gears"} }],
  ["/enterprise/%D0%90%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%B0/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/Архитектура/index.html.js"), meta: {"t":"Архитектура решения","O":1} }],
  ["/enterprise/%D0%9D%D0%BE%D0%B2%D0%B0%D1%8F%20%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/Новая версия/index.html.js"), meta: {"t":"Список функций, которых нет, но планируются","i":"star"} }],
  ["/enterprise/%D0%9E%D0%B1%D1%81%D0%BB%D1%83%D0%B6%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/Обслуживание/index.html.js"), meta: {"t":"Задачи администрирования","i":"handshake-angle","O":4} }],
  ["/enterprise/%D0%9E%D0%B1%D0%B5%D1%81%D0%BF%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D0%B8/auth.html", { loader: () => import(/* webpackChunkName: "auth.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/Обеспечение безопасности/auth.html.js"), meta: {"t":"Авторизация","O":3} }],
  ["/enterprise/%D0%9E%D0%B1%D0%B5%D1%81%D0%BF%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D0%B8/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/Обеспечение безопасности/index.html.js"), meta: {"t":"Обеспечение информационной безопасности","i":"lock"} }],
  ["/enterprise/%D0%9E%D0%B1%D0%B5%D1%81%D0%BF%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D0%B8/siem.html", { loader: () => import(/* webpackChunkName: "siem.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/Обеспечение безопасности/siem.html.js"), meta: {"t":"SIEM","O":3} }],
  ["/enterprise/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0/FULL_INSTALL.html", { loader: () => import(/* webpackChunkName: "FULL_INSTALL.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/Установка/FULL_INSTALL.html.js"), meta: {"t":"Prodution-ready установка","i":"","O":-1} }],
  ["/enterprise/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0/GET_STARTED.html", { loader: () => import(/* webpackChunkName: "GET_STARTED.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/Установка/GET_STARTED.html.js"), meta: {"t":"Get started","i":"","O":-1} }],
  ["/enterprise/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/enterprise/Установка/index.html.js"), meta: {"t":"Установка","O":2} }],
  ["/features_new_storm/2)%20%D0%A0%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%20BPMN/2_appruval.html", { loader: () => import(/* webpackChunkName: "2_appruval.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/2) Редактор BPMN/2_appruval.html.js"), meta: {"t":"Согласование","i":"","O":-4} }],
  ["/features_new_storm/2)%20%D0%A0%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%20BPMN/2_bpmn_calc_duration.html", { loader: () => import(/* webpackChunkName: "2_bpmn_calc_duration.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/2) Редактор BPMN/2_bpmn_calc_duration.html.js"), meta: {"t":"Расчёт длительности сценария","i":"","O":-6} }],
  ["/features_new_storm/2)%20%D0%A0%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%20BPMN/2_bpmn_scoring.html", { loader: () => import(/* webpackChunkName: "2_bpmn_scoring.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/2) Редактор BPMN/2_bpmn_scoring.html.js"), meta: {"t":"Оценка качества","i":"","O":-7} }],
  ["/features_new_storm/2)%20%D0%A0%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%20BPMN/2_connection_diagram.html", { loader: () => import(/* webpackChunkName: "2_connection_diagram.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/2) Редактор BPMN/2_connection_diagram.html.js"), meta: {"t":"Связь между диаграммами","i":"","O":-2} }],
  ["/features_new_storm/2)%20%D0%A0%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%20BPMN/2_import.html", { loader: () => import(/* webpackChunkName: "2_import.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/2) Редактор BPMN/2_import.html.js"), meta: {"t":"Импорт диаграмм","i":"","O":-3} }],
  ["/features_new_storm/2)%20%D0%A0%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%20BPMN/2_sub_process.html", { loader: () => import(/* webpackChunkName: "2_sub_process.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/2) Редактор BPMN/2_sub_process.html.js"), meta: {"t":"Декомпозиция, Подпроцесс","i":"","O":-1} }],
  ["/features_new_storm/2)%20%D0%A0%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%20BPMN/2_versioning.html", { loader: () => import(/* webpackChunkName: "2_versioning.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/2) Редактор BPMN/2_versioning.html.js"), meta: {"t":"Версионирование","i":"","O":-5} }],
  ["/features_new_storm/2)%20%D0%A0%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%20BPMN/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/2) Редактор BPMN/index.html.js"), meta: {"t":"New Шторм. Редактор BPMN","O":1} }],
  ["/features_new_storm/6)%20%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B%20%D0%B0%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D1%8B/5_create-ea.html", { loader: () => import(/* webpackChunkName: "5_create-ea.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/6) Элементы архитектуры/5_create-ea.html.js"), meta: {"t":"Создание ЭА","i":"","O":-3} }],
  ["/features_new_storm/6)%20%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B%20%D0%B0%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D1%8B/5_custom-ea.html", { loader: () => import(/* webpackChunkName: "5_custom-ea.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/6) Элементы архитектуры/5_custom-ea.html.js"), meta: {"t":"Кастомные ЭА","i":"","O":-1} }],
  ["/features_new_storm/6)%20%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B%20%D0%B0%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D1%8B/5_edit_delete-ea.html", { loader: () => import(/* webpackChunkName: "5_edit_delete-ea.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/6) Элементы архитектуры/5_edit_delete-ea.html.js"), meta: {"t":"Редактирование ЭА","i":"","O":-2} }],
  ["/features_new_storm/6)%20%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B%20%D0%B0%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D1%8B/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/features_new_storm/6) Элементы архитектуры/index.html.js"), meta: {"t":"New Шторм. Элементы архитектуры","O":5} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/stormbpmn-documentation/src/.vuepress/.temp/pages/404.html.js"), meta: {"t":""} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
